### ISSUE TITLE
Does not compile with current zig

### ISSUE THREAD

**Issue by bortzmeyer** [remeh/statsd-zig#2]
The build system changed a lot and ` zig build` now no longer works (several bugs).

**Comment by remeh** [comment]
Hey @bortzmeyer, thank you for the message. I'll port this to latest Zig when I'll have some time 👍 I'll update here once it's done.

**Comment by remeh** [comment]
Hey @bortzmeyer, the project now compiles with Zig stable 0.11.0. :+1:
